=== ayushsaini781808-lab/Web-technology/XML/student4/student.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (rollno, name, course, branch)>
<!ELEMENT rollno (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ELEMENT branch (#PCDATA)>

=== ayushsaini781808-lab/Web-technology/student4/student.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/css" href="student.css"?>

<!DOCTYPE students SYSTEM "student.dtd">

<students>
    <student>
        <rollno>101</rollno>
        <name>Dhruv</name>
        <course>B.Tech</course>
        <branch>CSE</branch>
    </student>

    <student>
        <rollno>102</rollno>
        <name>Ayush</name>
        <course>B.Tech</course>
        <branch>IT</branch>
    </student>

    <student>
        <rollno>103</rollno>
        <name>Deepak</name>
        <course>BCA</course>
        <branch>Computer Science</branch>
    </student>
</students>
